### ISSUE TITLE
Add more detailed information after failed verification

### ISSUE THREAD

**Issue by qooban** [edk-software/edk-route-verifier#34]
Available options:
1. Popup on hovering box related to failed verification
2. Full report of all logs or report of all errors (already gathered) on new button click

**Comment by zaquncio** [comment]
Spoko

**Comment by quchasz** [comment]
Please raise the severity of this enhancement request, if possible.

**Comment by qooban** [comment]
@quchasz What are you're suggestions here? What would be the best way of info presentation about failed verification?

**Comment by quchasz** [comment]
You can use similar way to report verification errors like you do for successful verification - but instead of green popup you can display a red one with errors report, without timer, so user will be forced to close it manually.

The errors report below verifier icons is also fine, so simply choose the fastest or more comfortable solution.

**Comment by qooban** [comment]
One problem here is that I don't have language support - I would need to extend route page to pass the information from rejony-app to edk-route-verifier about currently chosen language and basing on that present message in either PL or EN.

The quickest way to get more information what's wrong with the route 
(in the meantime when you're waiting for my implementation) is:
1. Go to browser console (**F12** shortcut in most of the browsers)
2. Run verification
3. See errors and warning in the console

If you want detailed information what is going on in verifer, in the console:
1. Write `setLogLevel('debug')` and press **Enter**
2. Run verification
3. See detailed logs in the console

**Comment by qooban** [comment]
Working version without language support:
![obraz](https://user-images.githubusercontent.com/5202105/54978914-f7f70200-4fa1-11e9-9575-4892179e6206.png)

I'm also thinking of having popups with error on mouse hover on failed boxes.

**Comment by zaquncio** [comment]
@duzymaju jak można to zintegrować, aby dało się tłumaczyć te komunikaty?

**Comment by duzymaju** [comment]
@zaquncio I think the only reasonable way is to add required translations, some of them with placeholders (e.g. `Station %d found %d times` or even `Station %d found %d time|Station %d found %d times`), to the object which has to be passed to Verifier via inline JS or `data`-like HTML attribute (template).

**Comment by qooban** [comment]
@duzymaju What do you think about just passing `data`-like HTML attribute with language value (`pl` or `en`)? That way I can handle all the translation stuff inside verifier.

**Comment by duzymaju** [comment]
I was thinking about having everything in one lace but it sounds simplier and even more pure to keep verifier's translations in it's repo because technically it's separate app. So let's do it that way - where to put `data-lang="pl"` attribute?
BTW: in theory `rejony-app` can set `data-lang` value which doesn't exist in verifier, so for such case (or for case that there's no `data-lang` attribute) set default language.

**Comment by qooban** [comment]
Currently all `data-*` HTML attributes used by are defined inside `div#map-canvas` in `src/WIO/EdkBundle/Resources/views/EdkRoute/info.html.twig`. Maybe there?

Or maybe we should move all that attributes to element more related to verifer, e.g. `button#verifyRoute`?

**Comment by qooban** [comment]
@duzymaju Or maybe just set lang attribute in `<html class="no-js" lang="en">` properly? I noticed that it is always set to 'en' no matter what language you set in user profile.

**Comment by duzymaju** [comment]
I like your latest idea the most! Done ([#141](https://github.com/edk-software/rejony-app/pull/141))!

**Comment by qooban** [comment]
Released within https://github.com/edk-software/edk-route-verifier/releases/tag/v1.3.0
