### ISSUE TITLE
Update code to ES6

### ISSUE THREAD

**Issue by qooban** [edk-software/edk-route-verifier#43]

**Comment by turisap** [comment]
Hi @qooban, I'm currently looking for getting experience in contribution to open-source and would like to try your task if it's not complicated. I'm a newbie to contribution and it would be great if you could provide me with some instructions. Thanks)

**Comment by qooban** [comment]
Hi @turisap, thanks for contacting me. 


I'm open for your contribution, but I am in the middle of process of transferring this repo to `edk-software` organization, so... You can of course start working here, but you should be aware that you will need to switch to another repo soon.

>I'm a newbie to contribution and it would be great if you could provide me with some instructions.

I created this task to refactor all the code in `src` directory to take benefits of ES6, eg.:
- use classes,
- use arrow functions,
- use consts,
- use let instead of var where possible.
Are you familiar with ES6? I see it as a good way to get to enhance ES6 knowledge for the contributor.
ES6 features are nicely described at: http://es6-features.org

BTW How did you find this repository? ;-)

**Comment by turisap** [comment]
Hi @qooban, thanks for letting me in this project.

I can start with this repo and can move to another one afterwards..

> Are you familiar with ES6? 

Yes, I am, to a particular extent, thought. I can use the most usable features as arrow functions, array and objects destructing, let and var and classes, string templates, but I don't know all of them (like weakmaps  f.e.) and will be happy to learn them while updating your code. It would be great if you can give some feedback sometimes about on which feature to use :-)

> BTW How did you find this repository? ;-)

I found it through github search while looking for an issue to contribute. I think I found it by label 'good-first-issue'

I checked your repo and haven't found any contributing guides, so I've just forked the repo to start. Are there any rules I should know before I start or can I just begin straight away?

**Comment by qooban** [comment]
Hi @turisap. repo is already moved as you could probably already noticed (`https://github.com/edk-software/edk-route-verifier`). 

>I checked your repo and haven't found any contributing guides, so I've just forked the repo to start. Are there any rules I should know before I start or can I just begin straight away?

You can begin straight away. You can make some changes and let me know to check (using PR or just branch), we will see if the direction is good.

**Comment by turisap** [comment]
@qooban, I'm wondering if you know why all those commits I've made to the pull-request does not appear in my graph? 

As I'm still learning and trying to get some experience, it would be perfect if those commits show up in my profile so that I have something to show in the future :-)

**Comment by qooban** [comment]
I have squashed them into one commit : https://github.com/edk-software/edk-route-verifier/commit/e2911b63910b30693644ab8c8a29dbc65fb7dab4

Do you see it in your graph?
