### ISSUE TITLE
Add code style checker

### ISSUE THREAD

**Issue by qooban** [edk-software/edk-route-verifier#47]
Probably https://eslint.org/ would be the best option.

This task is to:
1. Add style checker to dependencies and configure it according to most commonly accepted rules
2. Create new build task in package.json for new style checker (that be executed with `npm run` - sth like lint or style-check)
3. Add style checker to be part of `CircleCI` integration process (that way invalid code won't be merged into master)

**Comment by turisap** [comment]
@qooban, can I get assigned to this issue?

I've already begun solving this issue and I want to ask you whether you have any preferences in terms of rules which will be used in ESLint? I've installed airbnb-base rules for the start. Please let me know if your project requires something different.

**Comment by qooban** [comment]
Sure, I have sent you invitation to collaboration in the project: https://github.com/edk-software/edk-route-verifier/invitations . Please check. Until you accept it I cannot assign this issue to you.

> I've already begun solving this issue and I want to ask you whether you have any preferences in terms of rules which will be used in ESLint? I've installed airbnb-base rules for the start. Please let me know if your project requires something different. 

Nothing special. Right now I think we should align to the most commonly used rules.

> Another question is on which directories should I run ESLint? I guess it should be src/**, but do I need to run it on tests and server ones?

Good question. For sure for `src`. In case of `test` and `server` folders... Hmm... Let's add it also, we'll see, if that become too strict for test code, we'll leave it only for `src`.

**Comment by qooban** [comment]
@turisap I have assigned you to both. I think you can switch from your fork to work directly on this (`edk-software/edk-route-verifier`) repository. That way, you'll get CircleCI verification after each commit to your branches. Let me know if there are any permission issues. You should be able to create and push your own branches and create pull requests to master branch.

**Comment by turisap** [comment]
@qooban, it works well actually, I've already pushed my local brunch `ESLint/#47` with initial sets.

**Comment by qooban** [comment]
@turisap Please also add it to Circle CI configuration. It is in `.circleci/config.yaml`.

**Comment by qooban** [comment]
@turisap In terms of contribution graph - here is description how it works I suppose: https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/ . If you want me to care about sth in terms of your contributions to `edk-route-verifier` please let me know.

**Comment by turisap** [comment]
@qooban, yes, I saw one commit in my graph, but expected that all my work over the last days would be seen there, I got an empty week.
It would be perfect to have it seen as well as other contributions.

**Comment by qooban** [comment]
@turisap, what is worth more 1 big commit **with 11,549 additions and 3,193 deletions** or hundreds of commits each changing single lines? ;-) All your work is in the repository. If anybody ask you about amount of work you've done you can show it, it's more accurate measurement of activity. And after all noone can steal experience you've gained.

**Comment by turisap** [comment]
@qooban, ok let's leave it :-)
I'm wondering if you have any React.js projects I can participate in?

**Comment by qooban** [comment]
I'm in one. Please take a look at: https://github.com/cloudify-cosmo/cloudify-stage . It is open-sourced since few months. It's actually my current job - I'm working for Cloudify and I'm front-end dev, there.

Cannot promise anything, but I will let you know if there's any possibility to help there.

**Comment by turisap** [comment]
@qooban, I would be happy to participate :-)

**Comment by qooban** [comment]
Great work, @turisap ! Want to take another one? :-) If so, please take a look at issues list and let me know by commenting one you would like to take.

**Comment by turisap** [comment]
@qooban, I'm happy to participate :-)
I'd like to try something as bug fixing or new features development, so I'l take a look in the issues will let you know if there is anything which I'd like to work in.
