### ISSUE TITLE
route length cheated in the KML trace

### ISSUE THREAD

**Issue by quchasz** [edk-software/edk-route-verifier#59]
**Issue:**
User can cheat with the length of EDK route by drawing the path far away after 14th Station.

**Detailed issue description/reproduction steps:**
This issue has been discovered on one of routes prepared for the EDK2019 (https://my.edk.org.pl/s/WepzGGi3v1gm/routes/1730/info):
- according to the description in route details the EDK route has 20km,
- length of the path in KML file is 20,9km -> so test passes,
- however 14th Station is 5 km earlier then the end of route

Comparing above with the route description we see that EDK route ends on 14th Station (what is nothing surprising) while trace is much longer, drawn like that only to satisfy verifier requirements.

Both the KML trace and route description attached below:
[edk-map-route-1730.zip](https://github.com/edk-software/edk-route-verifier/files/2831195/edk-map-route-1730.zip)

**Proposed solution:**
Do not count the length of path behind 14th Station to pass length verification or limit possible length of path between 14th Station and end of patch to eg. 500 m.
The Contemplations end on 14th Station so there is no justification to draw the path behind it.

**Note 1:**
This kind of issues can become common problem with paths in the EDK2019 edition when we make a pressure to limit numer of routes "like EDK" type (where minimal length is 20km).

**Note 2:**
This issue is related a bit with issue #37

**Comment by qooban** [comment]
Got it. Agree with the solution.

Btw when we have KML parser (https://github.com/edk-software/rejony-app/issues/116) will it cut the route above 14th station?

**Comment by quchasz** [comment]
No, KML parser will not modify route length.

**Comment by qooban** [comment]
@quchasz 

Implemented this issue the following way:
- when Station XIV is present path length is calculated from the beginning to the point on path which is nearest the Station XIV poing
- when Station XIV is not present path length is calculated as it was till now (verification will fail anyway, but I need to have fallback for that case).

It is not merged, yet. In my development tests I've got three routes which ends after Station XIV (I've got some old KML files from last years), so please confirm it is fully accepted solution.

If you confirm it, I'll merge it and create new version.

**Comment by quchasz** [comment]
@qooban 

There is no strong enough justification to allow path exceed the Station XIV, so I accept solution proposed.

However this year we all are surprised with Station XV added to Contemplations ;)

**Comment by qooban** [comment]
Merged #77. Station XV :1st_place_medal:
