### ISSUE TITLE
limit distance allowed between the path and the Station point

### ISSUE THREAD

**Issue by quchasz** [edk-software/edk-route-verifier#60]
Currently distance between the path and the Station points is allowed up to 100m. I think it is too far - Stations should be located on the path (close to the path) so I propose to limit it to 50m.

This will impact on the quality of KML traces.

**Comment by qooban** [comment]
Easy to change, but that'll affect all the routes. We had discussion last edition about it. Originally it was 50m, but I was pressed to increase it to 100m. Do we really want to decrease the allowed distance between the path and the Station points?

**Comment by quchasz** [comment]
The enhancement requested here will impact only routes where user executes verification - routes already verified and approved for EDK 2019 remain unaffected until next verifier execution, eg. as result of KML update.

The idea behind this request is to make a pressure on users to improve the quality of traces they draw, so I suggest to do it.

**Comment by qooban** [comment]
Got it. Agree. Added to **EDK 2019 milestone**.

**Comment by qooban** [comment]
Implemented within #68 .
