### ISSUE TITLE
Route type icon style differs comparing to remaining icons

### ISSUE THREAD

**Issue by quchasz** [edk-software/edk-route-verifier#65]
The "Route type" icon style differs to remaining icons both before and after route validation attempt - it stays navy blue regardless verification has passed, has failed or has not been done:
![screen shot 2019-03-05 at 06 37 01](https://user-images.githubusercontent.com/47346557/53783728-14f46400-3f13-11e9-8a7a-4e3104f340d8.png)

![screen shot 2019-03-05 at 06 37 14](https://user-images.githubusercontent.com/47346557/53783736-1c1b7200-3f13-11e9-8f73-fee18bcdc33b.png)

Issue is minor (cosmetic) but makes some doubts, so taking into account it is very simple to correct please solve it before nearest release.

**Comment by qooban** [comment]
So the color of the icon will be either light gray (before verification) or green (after verification) as this is just indication if that is EDK route or only Inspired route => It will always be valid. Please correct me if I'm wrong.

**Comment by quchasz** [comment]
Actually it should behaves like other tests, so:
- light grey at the beginning, before verification attempt,
- if the trace does not meet 'full route' conditions, but is set as 'full route' the test fails, so icon should change to orange,
- if the trace meets 'full route' conditions, but is set as 'only inspired route' the test fails, so icon should change to orange
- and finally if conditions and type match the test passes, so icon should change to green.

In case if all other tests pass but only route type is wrong the overall result is failed, but icon colour do not indicate that type needs to be changed:
![screen shot 2019-03-05 at 09 17 09](https://user-images.githubusercontent.com/47346557/53790633-b980a100-3f27-11e9-88b4-25acba0a22de.png)

Above scenario makes some doubts for some leaders.

**Comment by qooban** [comment]
Not sure about the solution.

Let's take a look not only at Route Type, but also at the Route Length, Elevation Gain, Elevation Loss, Elevation Total Change - these field are always green after successful calculation. These are not verified, only calculated from KML file.

I think that what we can improve in that matter is maybe add logical separation => transform layout to show two groups of elements:
1. Calculated (Route Length, Route Type, Elevation Gain, Elevation Loss, Elevation Total Change)
2. Verified (One Route, Station Numbering and Naming, Station Order, Station Placement, Data Consistency)

There are 5 elements in each group, so we can maybe present in two columns. What do you think?

**Comment by quchasz** [comment]
Actually if you decide to improve it in any way I think you should take into consideration to put minimal effort in it because routes management requires deeper analysis and improvement.

Why region leader is forced to manually enter route length, elevation gain and the route type while those are easy to propagate from kml, don't you think?

Next, we can not be sure whether 'only inspired routes' will be allowed next year, so maybe this subject matters only 6 weeks from now...

Maybe just force the icon to behaves like other calculated? Or ignore this issue...

**Comment by qooban** [comment]
OK, I see.

> Why region leader is forced to manually enter route length, elevation gain and the route type while those are easy to propagate from kml, don't you think?
Yeah, I fully agree, and I'm aware of that issue. That should be done automatically.

> Maybe just force the icon to behaves like other calculated? Or ignore this issue...
I will force the icon to behave like other calculated: color of the icon will be either light gray (before verification) or green (after verification).

**Comment by qooban** [comment]
Implemented within #69 .
