### ISSUE TITLE
Approved route remains approved even if route properties changes

### ISSUE THREAD

**Issue by quchasz** [edk-software/edk-route-verifier#66]
Reproduction steps:

1. Have route with approved status
2. Edit route properties - change distance, elevation or type (it does not force route status change, while it should, however this applies to rejony-app not to verifier)
3. Run the verifier -> **even if result is failed the route status remains unchanged, what is defect** 

Thank to the above leader is able to create 'only inspired route', get it approved and then change it's type to 'full route'.

**Comment by qooban** [comment]
Yeah, but if we fix that part on rejony-app (https://github.com/edk-software/rejony-app/issues/120), then there will be no issue on verifier. Any change of the route parameters in rejony-app should move that route to not verified/not approved state.

Route verifier was meant only to automatically accept if everthing, according to specific rules, in the route is fine, not to manipulate the route status. I would leave it as it is until we have really a need to manipulate status from route verifier. Are you OK with making that issue invalid? Or at least postponing it after EDK 2019?

**Comment by quchasz** [comment]
You are correct, leave it as it works now. Close the issue as invalid, please.
