### ISSUE TITLE
invalid verification result on kml with one path but without stations

### ISSUE THREAD

**Issue by quchasz** [edk-software/edk-route-verifier#70]
It seems that verification result is error on all tests for the kml file where:
- there is 1 path
- there are no Stations

In such case the 'One route' test should pass.

The kml on which issue reproduces:
[Poznań_Klerycy_blNarcyza-Putza_2019_02.kml.zip](https://github.com/edk-software/edk-route-verifier/files/2945194/Poznan_Klerycy_blNarcyza-Putza_2019_02.kml.zip)

**Comment by qooban** [comment]
True. I treat the cases:
1. route without any point
2. route without any path
as unverifiable, that's why everything is orange, but I can change that.

Should be quick. Moving to **EDK 2019 milestone**.

**Comment by qooban** [comment]
Fixed in #71 .
