### ISSUE TITLE
The route elevation profile improvement

### ISSUE THREAD

**Issue by quchasz** [edk-software/edk-route-verifier#73]
The elevation profile in the shape it is available today is useless - it shows the route profile only after the successful validation, if user manually closes the green popup:
![Screen Shot 2019-03-13 at 08 22 23](https://user-images.githubusercontent.com/47346557/54260600-a5612300-4569-11e9-9891-4fb35205fec5.png)
or after failed validation.

Without validation attempt the elevation profile remains empty.

From this reason it should be either removed at all or loaded on the page load event. I'm even not sure whether it should be related in any way to verifier, it should be rather element of the route page.

**Comment by qooban** [comment]
There's another solution here. There's an idea of uploading the profile to database after verification. 
See: https://github.com/edk-software/rejony-app/issues/44

**Comment by quchasz** [comment]
It's perfect! Nothing more is needed.

**Comment by qooban** [comment]
Added to next year's edition.

**Comment by qooban** [comment]
Obsoleted by [Create Verify API](https://github.com/edk-software/edk-route-verifier/milestone/3) milestone and https://github.com/edk-software/rejony-app/pull/149. The route elevation profile will be stored in DB and loaded on page open.
